# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
name: Create new release
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  CreateRelease:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
        
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: "v"
          dry_run: true
          default_bump: false

      - name: Set Configurations
        if: steps.tag_version.outputs.release_type
        shell: bash
        env:
          OLD_VERSION: ${{ steps.tag_version.outputs.previous_version }}
          VERSION: ${{ steps.tag_version.outputs.new_version }}
        run: sed -ri "s/$OLD_VERSION/$VERSION/" "package.json" || exit 1

      - uses: EndBug/add-and-commit@v9
        if: steps.tag_version.outputs.release_type
        with:
          message: Update Version to ${{ steps.tag_version.outputs.new_version }}
          committer_name: GitHub Actions
          committer_email: actions@github.com
          add: package.json

      - uses: actions/setup-node@v3.5.1
        if: steps.tag_version.outputs.release_type
      - run: npm ci
        if: steps.tag_version.outputs.release_type
      - name: Publish to Visual Studio Marketplace
        if: steps.tag_version.outputs.release_type
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: ${{ secrets.ADO_PAT }}
          registryUrl: https://marketplace.visualstudio.com
